# Generated by Django 2.1.1 on 2019-03-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190321_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('project_task', 'project task'),)},
        ),
    ]
