# Generated by Django 2.1.1 on 2019-03-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190321_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
    ]
